# Use vi mode
set -o vi

# PROMPT CONFIG
source ~/.bash_prompt

# COLOR COMMANDS
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -G'
alias grep='grep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias egrep='egrep --colour=auto'

# ALIASES
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'
alias mci='mvn clean install'
alias mcis='mvn clean install -DskipTests'
alias mbr='mvn spring-boot:run'
alias mbrr='register_cwd_artefact && mbr'

export EDITOR="vim"

# Source bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# Initialise jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

if [ -f ~/.bash_functions ]; then
	. ~/.bash_functions
fi

# NVM Setup
export NVM_DIR="$HOME/.nvm"
. $(brew --prefix nvm)/nvm.sh 
